name: Reliability Gate

on:
  pull_request:
    branches: [ main ]

jobs:
  reliability-gate:
    name: Test Reliability Gate
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important to fetch full history for git diff

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Adjust to match your project's Java version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run reliability gate
        run: ./gradlew reliabilityGate